import numpy as np


#Function to load numeric grades from CSV (skips names)
def load_grades(filename):
    """
    Loads numeric grades from CSV into a numpy array.
    Skips the first two columns (First Name, Last Name) and header row.
    """
    data = np.genfromtxt(filename, delimiter=',', skip_header=1, usecols=(2, 3, 4))
    return data


#Function to calculate statistics for each exam in columns
def exam_statistics(grades):
    print("Exam-wise Statistics:")
    for i in range(grades.shape[1]):
        exam = grades[:, i]
        print(f"Exam {i + 1}:")
        print(f"  Mean: {np.mean(exam):.2f}")
        print(f"  Median: {np.median(exam):.2f}")
        print(f"  Std Dev: {np.std(exam):.2f}")
        print(f"  Min: {np.min(exam):.2f}")
        print(f"  Max: {np.max(exam):.2f}")
        print()


#Function to calculate the overall statistics for all exams
def overall_statistics(grades):
    all_grades = grades.flatten()
    print("Overall Statistics:")
    print(f"  Mean: {np.mean(all_grades):.2f}")
    print(f"  Median: {np.median(all_grades):.2f}")
    print(f"  Std Dev: {np.std(all_grades):.2f}")
    print(f"  Min: {np.min(all_grades):.2f}")
    print(f"  Max: {np.max(all_grades):.2f}")
    print()


#Function to calculate statistics for passing and failing grades
def pass_fail_statistics(grades, passing_grade=60):
    print("Pass/Fail Statistics per Exam:")
    for i in range(grades.shape[1]):
        exam = grades[:, i]
        passed = np.sum(exam >= passing_grade)
        failed = np.sum(exam < passing_grade)
        print(f"Exam {i + 1}: Passed: {passed}, Failed: {failed}")

    total_grades = grades.size
    total_passed = np.sum(grades >= passing_grade)
    pass_percentage = (total_passed / total_grades) * 100
    print(f"\nOverall Pass Percentage across all exams: {pass_percentage:.2f}%\n")


#Main execution
if __name__ == "__main__":
    filename = "grades.csv"  # CSV generated by your first script
    grades = load_grades(filename)

    print("First few rows of the numeric grades:")
    print(grades[:5])  # Print first 5 rows
    print()

    exam_statistics(grades)
    overall_statistics(grades)
    pass_fail_statistics(grades)
